import { isSupabaseConfigured } from "./lib/supabase.js";
import { ensureGuestSession } from "./services/auth.js";
import { uploadAvatar } from "./services/storage.js";
import {
  addPlayer as addRemotePlayer,
  createRoom as createRemoteRoom,
  deleteRoom as deleteRemoteRoom,
  expirePendingItem as expireRemoteItem,
  findRoom as findRemoteRoom,
  listRooms as listRemoteRooms,
  removePlayer as removeRemotePlayer,
  rollD20 as rollRemoteD20,
  startRace as startRemoteRace,
  subscribeToRoom,
  useItem as useRemoteItem
} from "./services/rooms.js";

const $ = (selector) => document.querySelector(selector);
const STORAGE_KEY = "d20-racing-rooms-v2";
const colors = ["#ff5a1f", "#38bdf8", "#a78bfa", "#39e58c", "#fbbf24", "#fb7185"];
const state = { rooms: loadRooms(), room: null, pilots: [], laps: 3, turn: 0, racing: false, photo: "", guestId: getGuestId(), cloud: false, unsubscribe: null, pendingExpiryTimer: null, pendingCountdown: null, lastEventId: "none", giftEventTimer: null };

function loadRooms() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; } catch { return []; } }
function getGuestId() { let id=localStorage.getItem("d20-racing-guest-id"); if(!id){id=crypto.randomUUID?.()||`guest-${Date.now()}-${Math.random()}`;localStorage.setItem("d20-racing-guest-id",id);} return id; }
function isHost() { return state.room?.ownerId===state.guestId; }
function ownsPilot(pilot) { return pilot?.ownerId===state.guestId; }
function canRollCurrentPilot() { return isHost()||ownsPilot(state.pilots[state.turn]); }
function saveRooms() { if(state.cloud)return;try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.rooms)); } catch { toast("O navegador ficou sem espaço para salvar mais fotos."); } }
function escapeHTML(value) { return String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function toast(message) { const el=$("#toast"); el.textContent=message; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2200); }
function showOnly(...ids) { document.querySelectorAll(".page").forEach(el=>el.hidden=!ids.includes(el.id)); }
function generateCode() { const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let code=""; do { code=Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join(""); } while(state.rooms.some(r=>r.code===code)); return code; }

function makeAvatar(seed="D20") { const initials=seed.slice(0,2).toUpperCase(),color=colors[Math.floor(Math.random()*colors.length)]; const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="160" height="160" fill="${color}"/><circle cx="80" cy="62" r="31" fill="#f6d2b8"/><path d="M22 160c4-44 26-65 58-65s54 21 58 65" fill="#07111f"/><path d="M48 55c2-28 18-40 35-40 20 0 35 16 35 43-13-7-23-18-29-28-8 12-24 22-41 25z" fill="#15263a"/><text x="80" y="145" text-anchor="middle" font-family="Arial" font-weight="bold" font-size="18" fill="white">${initials}</text></svg>`; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`; }
function setPhoto(src) { state.photo=src; const p=$("#photoPreview"); p.textContent=""; p.style.backgroundImage=`url("${src}")`; }

function normalizePlayer(player){return {id:player.id,ownerId:player.owner_id,name:player.codename,photo:player.avatar_url||makeAvatar(player.codename),score:player.score||0,rolls:player.roll_count||0};}
function normalizeRoom(room){return {id:room.id,code:room.code,name:room.name,laps:room.laps,ownerId:room.owner_id,status:room.status,currentPlayerId:room.current_player_id,pendingItem:room.pending_item,lastEvent:room.last_event,winnerId:room.winner_id,pilots:(room.players||[]).map(normalizePlayer),createdAt:room.created_at};}
async function reloadRemoteRooms(){state.rooms=(await listRemoteRooms()).map(normalizeRoom);renderDashboard();}
async function refreshCurrentRoom(){if(!state.cloud||!state.room)return;const remote=await findRemoteRoom(state.room.code);if(!remote){goDashboard();toast("A sala foi encerrada.");return;}const room=normalizeRoom(remote);state.room=room;state.pilots=room.pilots;state.rooms=state.rooms.map(r=>r.code===room.code?room:r);state.turn=Math.max(0,state.pilots.findIndex(p=>p.id===room.currentPlayerId));processPublicGiftEvent(room);if(room.status==="racing"){state.racing=true;$("#activeRaceName").textContent=room.name;$("#raceCode").textContent=`SALA ${room.code}`;$("#raceLapSummary").textContent=`${room.laps} ${room.laps===1?"VOLTA":"VOLTAS"}`;showOnly("raceSection");renderRace();updateRollPermission();if(room.pendingItem){schedulePendingExpiry(room.pendingItem);const source=state.pilots.find(p=>p.id===room.pendingItem.player_id);if(ownsPilot(source))showRemoteItem(room.pendingItem);else hideRemoteItem(true);}else hideRemoteItem();}else if(room.status==="finished"&&room.winnerId){hideRemoteItem();state.racing=false;showOnly("raceSection");renderRace();const winner=state.pilots.find(p=>p.id===room.winnerId);if(winner)showWinner(winner);}else{hideRemoteItem();renderGrid();}}

function renderDashboard() {
  $("#headerStatus").textContent="Dashboard"; $("#roomCount").textContent=state.rooms.length; $("#roomsEmpty").hidden=state.rooms.length>0;
  $("#roomsGrid").innerHTML=state.rooms.map(room=>`<article class="room-card"><small>SALA ${room.code}</small><h3>${escapeHTML(room.name)}</h3><div class="room-card-meta"><span>${room.laps} VOLTAS</span><span>${room.pilots?.length||0} PILOTOS</span></div><button data-code="${room.code}">ABRIR SALA →</button></article>`).join("");
}
async function goDashboard(){if(state.unsubscribe){state.unsubscribe();state.unsubscribe=null;}hideRemoteItem();state.room=null;state.pilots=[];state.racing=false;history.replaceState(null,"",location.pathname);showOnly("dashboard");if(state.cloud)await reloadRemoteRooms();else renderDashboard();scrollTo({top:0});}
async function removeCurrentRoom(){if(!state.room)return;if(state.cloud)await deleteRemoteRoom(state.room.id);else{state.rooms=state.rooms.filter(room=>room.code!==state.room.code);saveRooms();}await goDashboard();}
async function leaveCurrentRoom(){if(!state.room)return;const hostLeaving=isHost(),ownPilot=state.pilots.find(p=>ownsPilot(p)),roomName=state.room.name;if(state.cloud){if(ownPilot)await removeRemotePlayer(ownPilot.id);await goDashboard();}else{if(ownPilot){state.pilots=state.pilots.filter(p=>p.id!==ownPilot.id);syncRoom();}if(state.pilots.length===0&&(ownPilot||hostLeaving))await removeCurrentRoom();else await goDashboard();}toast(ownPilot?`Você saiu de ${roomName}. Seu corredor foi removido.`:`Você saiu de ${roomName}.`);}
function openRoom(room) {
  if(!room.ownerId&&!state.cloud){room.ownerId=state.guestId;saveRooms();}
  state.room=room; state.pilots=room.pilots||[]; state.laps=room.laps; state.racing=false;state.lastEventId=room.lastEvent?.id||"none";
  $("#roomCodeLabel").textContent=room.code; $("#roomRaceName").textContent=room.name; $("#roomLaps").textContent=`${room.laps} ${room.laps===1?"volta":"voltas"}`; $("#headerStatus").textContent=`Sala ${room.code}`;
  $("#deleteRoom").hidden=!isHost(); history.replaceState(null,"",`${location.pathname}?sala=${room.code}`); showOnly("lobby","gridSection"); renderGrid(); scrollTo({top:0});if(state.cloud&&room.id){if(state.unsubscribe)state.unsubscribe();state.unsubscribe=subscribeToRoom(room.id,()=>refreshCurrentRoom().catch(error=>toast(error.message)));}
}
function syncRoom() { if(!state.room||state.cloud)return; state.room.pilots=state.pilots; const i=state.rooms.findIndex(r=>r.code===state.room.code); if(i>=0)state.rooms[i]=state.room; saveRooms(); }

$("#showCreateRoom").onclick=()=>{showOnly("createRoomPage"); $("#headerStatus").textContent="Nova sala";};
$("#homeButton").onclick=goDashboard;
$("#leaveRoom").onclick=()=>{if(confirm("Sair da sala? Seu corredor será removido do grid."))leaveCurrentRoom();};
$("#leaveRace").onclick=()=>{if(confirm("Sair da corrida? Seu corredor será removido do grid."))leaveCurrentRoom();};
$("#deleteRoom").onclick=async()=>{if(!isHost())return toast("Somente o criador pode excluir a sala.");if(confirm("Excluir esta sala e todos os corredores? Esta ação não pode ser desfeita.")){try{await removeCurrentRoom();toast("Sala excluída.");}catch(error){toast(error.message);}}};
document.querySelectorAll(".lap-picker button").forEach(btn=>btn.onclick=()=>{state.laps=Math.max(1,Math.min(12,state.laps+Number(btn.dataset.step))); $("#lapDisplay").textContent=state.laps;});
document.querySelectorAll(".lap-quick button").forEach(btn=>btn.onclick=()=>{state.laps=Number(btn.dataset.laps);$("#lapDisplay").textContent=state.laps;document.querySelectorAll(".lap-quick button").forEach(b=>b.classList.toggle("selected",b===btn));});
$("#createRoomForm").onsubmit=async e=>{e.preventDefault();try{let room;if(state.cloud)room=normalizeRoom(await createRemoteRoom({name:$("#raceName").value.trim(),laps:state.laps}));else{room={code:generateCode(),name:$("#raceName").value.trim(),laps:state.laps,pilots:[],ownerId:state.guestId,createdAt:Date.now()};state.rooms.unshift(room);saveRooms();}e.target.reset();openRoom(room);toast(`Sala ${room.code} criada!`);}catch(error){toast(error.message);}};
$("#joinRoomForm").onsubmit=async e=>{e.preventDefault();try{const code=$("#roomCodeInput").value.trim().toUpperCase();const room=state.cloud?normalizeRoom(await findRemoteRoom(code)):state.rooms.find(r=>r.code===code);if(!room)return toast("Sala não encontrada.");openRoom(room);}catch(error){toast(error.message);}};
$("#roomsGrid").onclick=e=>{const btn=e.target.closest("[data-code]"); if(btn)openRoom(state.rooms.find(r=>r.code===btn.dataset.code));};
$("#copyCode").onclick=async()=>{const url=`${location.origin}${location.pathname}?sala=${state.room.code}`; try{await navigator.clipboard.writeText(url);toast("Link da sala copiado!");}catch{toast(`Código: ${state.room.code}`);}};

function handleImage(file) { if(!file?.type.startsWith("image/"))return toast("Solte um arquivo de imagem."); if(file.size>4*1024*1024)return toast("Escolha uma imagem de até 4 MB."); const reader=new FileReader(); reader.onload=()=>{const img=new Image();img.onload=()=>{const size=320,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;canvas.width=size;canvas.height=size;ctx.drawImage(img,sx,sy,side,side,0,0,size,size);setPhoto(canvas.toDataURL("image/jpeg",.82));};img.src=reader.result;}; reader.readAsDataURL(file); }
$("#photoInput").onchange=e=>handleImage(e.target.files[0]);
const drop=$("#photoDropzone"); ["dragenter","dragover"].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add("dragging");})); ["dragleave","drop"].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove("dragging");})); drop.addEventListener("drop",e=>handleImage(e.dataTransfer.files[0]));
$("#randomAvatar").onclick=()=>setPhoto(makeAvatar($("#codename").value||"D20")); $("#codename").oninput=e=>$("#charCount").textContent=`${e.target.value.length}/16`;

$("#joinForm").onsubmit=async e=>{e.preventDefault();if(state.pilots.some(p=>ownsPilot(p)))return toast("Você já criou seu corredor nesta sala.");const name=$("#codename").value.trim();if(state.pilots.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast("Esse codinome já está no grid.");try{if(state.cloud){const id=crypto.randomUUID(),photo=await uploadAvatar({userId:state.guestId,playerId:id,dataUrl:state.photo||makeAvatar(name)});await addRemotePlayer({id,roomId:state.room.id,codename:name,avatarUrl:photo});await refreshCurrentRoom();}else{state.pilots.push({id:crypto.randomUUID?.()||String(Date.now()),ownerId:state.guestId,name,photo:state.photo||makeAvatar(name),score:0,rolls:0});syncRoom();}e.target.reset();state.photo="";$("#photoPreview").style.backgroundImage="";$("#photoPreview").textContent="+";$("#charCount").textContent="0/16";renderGrid();toast(`${name} entrou na corrida!`);}catch(error){toast(error.message);}};
function renderGrid(){const alreadyJoined=state.pilots.some(p=>ownsPilot(p));$("#joinForm").hidden=alreadyJoined;$("#joinedMessage").hidden=!alreadyJoined;$("#roleBadge").textContent=isHost()?"DONO DA SALA":"VISITANTE";$("#roleBadge").classList.toggle("role-badge--host",isHost());$("#pilotCount").textContent=state.pilots.length;$("#emptyState").hidden=state.pilots.length>0;$("#pilotGrid").innerHTML=state.pilots.map((p,i)=>`<article class="pilot-card ${ownsPilot(p)?"pilot-card--mine":""}">${(isHost()||ownsPilot(p))?`<button class="remove-pilot" data-id="${p.id}" aria-label="Remover ${escapeHTML(p.name)}">×</button>`:""}<img src="${p.photo}" alt="Foto de ${escapeHTML(p.name)}"><h3>${escapeHTML(p.name)}</h3><small>PILOTO ${String(i+1).padStart(2,"0")}</small>${ownsPilot(p)?'<small class="pilot-owner">SEU CORREDOR</small>':""}</article>`).join("");const b=$("#startRace");b.disabled=state.pilots.length<2||!isHost();b.textContent=!isHost()?"AGUARDANDO O DONO DA SALA":state.pilots.length<2?"PRECISA DE 2 PILOTOS":`INICIAR ${state.room.laps} ${state.room.laps===1?"VOLTA":"VOLTAS"} →`;}
$("#pilotGrid").onclick=async e=>{const b=e.target.closest(".remove-pilot");if(!b)return;const pilot=state.pilots.find(p=>p.id===b.dataset.id);if(!isHost()&&!ownsPilot(pilot))return toast("Você não pode remover este corredor.");try{if(state.cloud){await removeRemotePlayer(pilot.id);await refreshCurrentRoom();}else{state.pilots=state.pilots.filter(p=>p.id!==b.dataset.id);syncRoom();renderGrid();}}catch(error){toast(error.message);}};

async function startRace(){if(!isHost())return toast("Somente o dono da sala pode iniciar a corrida.");try{if(state.cloud){await startRemoteRace(state.room.code);await refreshCurrentRoom();}else{state.pilots.forEach(p=>{p.score=0;p.rolls=0;p.claimedGifts=[];});state.turn=0;}state.racing=true;state.pendingGift=null;$("#activeRaceName").textContent=state.room.name;$("#raceCode").textContent=`SALA ${state.room.code}`;$("#raceLapSummary").textContent=`${state.room.laps} ${state.room.laps===1?"VOLTA":"VOLTAS"}`;$("#lastRoll").textContent="—";$("#winnerModal").hidden=true;$("#mysteryModal").hidden=true;showOnly("raceSection");renderRace();updateRollPermission();scrollTo({top:0});}catch(error){toast(error.message);}}
function renderRace(){const total=state.room.laps*100,track=$("#raceTrack");track.dataset.raceName=state.room.name;const markers=`<div class="track-marker marker-25">🎁<small>MARCO 25</small></div><div class="track-marker marker-50">🎁<small>MARCO 50</small></div><div class="track-marker marker-75">🎁<small>MARCO 75</small></div>`;track.innerHTML=markers+state.pilots.map((p,index)=>{const lap=Math.min(state.room.laps,Math.floor(p.score/100)+1),progress=p.score>=total?0:p.score%100,angle=(progress/100)*Math.PI*2,radiusX=42-(index%3)*2.6,radiusY=39-(index%3)*3,left=50+radiusX*Math.cos(angle),top=50+radiusY*Math.sin(angle),color=colors[index%colors.length];return `<div class="oval-racer" data-pilot="${p.id}" style="left:${left}%;top:${top}%;--racer-color:${color}"><img src="${p.photo}" alt=""><span class="racer-info"><strong>${escapeHTML(p.name)}</strong><i class="racer-lap">VOLTA ${lap}/${state.room.laps}</i><i>${Math.min(p.score,total)} / ${total}</i></span></div>`;}).join("");$("#currentPilot").textContent=state.pilots[state.turn]?.name||"—";}
function updateRollPermission(){const allowed=canRollCurrentPilot(),pilot=state.pilots[state.turn];$("#rollButton").disabled=!allowed;$("#turnPermission").textContent=allowed?(isHost()&&!ownsPilot(pilot)?"Controle do anfitrião":"É a sua vez de jogar"):`Aguardando ${pilot?.name||"o piloto"}`;}
function nextTurn(){state.turn=(state.turn+1)%state.pilots.length;setTimeout(()=>{$("#currentPilot").textContent=state.pilots[state.turn].name;updateRollPermission();},500);}
function crossedGiftMarker(pilot,from,to){pilot.claimedGifts=pilot.claimedGifts||[];const markers=[];for(let lap=0;lap<state.room.laps;lap++){for(const point of [25,50,75]){const absolute=lap*100+point,key=`${lap+1}-${point}`;if(from<absolute&&to>=absolute&&!pilot.claimedGifts.includes(key))markers.push({key,lap:lap+1,point,absolute});}}const marker=markers[0];if(marker)pilot.claimedGifts.push(marker.key);return marker;}
$("#startRace").onclick=startRace; $("#rollButton").onclick=()=>{if(!state.racing)return;if(!canRollCurrentPilot())return toast("Somente o dono deste corredor ou o anfitrião pode lançar.");const btn=$("#rollButton"),pilot=state.pilots[state.turn],total=state.room.laps*100;btn.disabled=true;let ticks=0;const timer=setInterval(async()=>{$("#lastRoll").textContent=Math.floor(Math.random()*20)+1;if(++ticks<9)return;clearInterval(timer);if(state.cloud){try{const result=await rollRemoteD20(state.room.code);$("#lastRoll").textContent=result.roll;await refreshCurrentRoom();updateRollPermission();}catch(error){toast(error.message);updateRollPermission();}return;}const roll=Math.floor(Math.random()*20)+1,previous=pilot.score;pilot.score+=roll;pilot.rolls++;const marker=crossedGiftMarker(pilot,previous,pilot.score);$("#lastRoll").textContent=roll;renderRace();if(pilot.score>=total){state.racing=false;setTimeout(()=>showWinner(pilot),850);}else if(marker){state.pendingGift=pilot;state.pendingMarker=marker;setTimeout(showMysteryGift,750);}else nextTurn();},65);};

const gifts=[{icon:"🐢",title:"CASCO D20",damage:15,text:"Escolha um rival para fazê-lo recuar 15 pontos."},{icon:"🍌",title:"BANANA CRÍTICA",damage:8,text:"Escolha um rival para fazê-lo recuar 8 pontos."},{icon:"⚡",title:"RAIO DO CAOS",damage:20,text:"Escolha um rival para fazê-lo recuar 20 pontos."},{icon:"🚀",title:"TURBO ÉPICO",boost:15,text:"Você avança mais 15 pontos imediatamente!"}];
function showMysteryGift(){const pilot=state.pendingGift,marker=state.pendingMarker;$("#giftIcon").textContent="🎁";$("#giftTitle").textContent=`PRESENTE DE ${pilot.name.toUpperCase()}`;$("#giftDescription").textContent=`Marco ${marker.point} da volta ${marker.lap}. Abra a caixa para descobrir o item.`;$("#openGift").hidden=false;$("#targetArea").hidden=true;$("#mysteryModal").hidden=false;}
function clearPendingTimers(){if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);if(state.pendingCountdown)clearInterval(state.pendingCountdown);state.pendingExpiryTimer=null;state.pendingCountdown=null;}
function hideRemoteItem(keepExpiryTimer=false){if(!state.cloud)return;if(state.pendingCountdown)clearInterval(state.pendingCountdown);state.pendingCountdown=null;if(!keepExpiryTimer){if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);state.pendingExpiryTimer=null;}$("#mysteryModal").hidden=true;$("#targetArea").hidden=true;}
function schedulePendingExpiry(item){if(!state.cloud||!state.room)return;if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);const expiresAt=new Date(item.expires_at||Date.now()+60000).getTime(),delay=Math.max(0,expiresAt-Date.now()+250),isItemOwner=ownsPilot(state.pilots.find(p=>p.id===item.player_id));state.pendingExpiryTimer=setTimeout(async()=>{try{const expired=await expireRemoteItem(state.room.code);if(expired){hideRemoteItem();if(isItemOwner)toast("O tempo do presente acabou. A vez foi perdida.");await refreshCurrentRoom();}}catch(error){toast(error.message);}},delay);}
function showRemoteItem(item){const icons={shell:"🐢",banana:"🍌",lightning:"⚡"},titles={shell:"CASCO D20",banana:"BANANA CRÍTICA",lightning:"RAIO DO CAOS"},expiresAt=new Date(item.expires_at||Date.now()+60000).getTime(),base=`Marco ${item.marker} da volta ${item.lap}. Escolha um rival para fazê-lo recuar ${item.damage} pontos.`;state.activeGift={damage:item.damage};state.pendingGift=state.pilots.find(p=>p.id===item.player_id);$("#giftIcon").textContent=icons[item.type]||"🎁";$("#giftTitle").textContent=titles[item.type]||"ITEM MISTERIOSO";$("#openGift").hidden=true;$("#targetGrid").innerHTML=state.pilots.filter(p=>p.id!==item.player_id).map(p=>`<button class="target-button" data-target="${p.id}"><img src="${p.photo}" alt=""><span>${escapeHTML(p.name)}</span></button>`).join("");$("#targetArea").hidden=false;$("#mysteryModal").hidden=false;if(state.pendingCountdown)clearInterval(state.pendingCountdown);const update=()=>{const seconds=Math.max(0,Math.ceil((expiresAt-Date.now())/1000));$("#giftDescription").textContent=`${base} Tempo restante: ${seconds}s.`;};update();state.pendingCountdown=setInterval(update,1000);}
function processPublicGiftEvent(room){const event=room.lastEvent;if(!event){state.lastEventId="none";return;}if(event.id===state.lastEventId)return;state.lastEventId=event.id;showPublicGiftEvent(event);}
function showPublicGiftEvent(event){if(state.giftEventTimer){clearInterval(state.giftEventTimer.interval);clearTimeout(state.giftEventTimer.reveal);clearTimeout(state.giftEventTimer.close);}const icons=["🐢","🍌","⚡","🚀"],finalIcons={shell:"🐢",banana:"🍌",lightning:"⚡",turbo:"🚀"},titles={shell:"CASCO D20!",banana:"BANANA CRÍTICA!",lightning:"RAIO DO CAOS!",turbo:"TURBO ÉPICO!"},source=state.pilots.find(p=>p.id===event.source_id),target=state.pilots.find(p=>p.id===event.target_id),modal=$("#giftEventModal"),card=modal.querySelector(".gift-event-card"),icon=$("#giftEventIcon");let index=0;card.classList.remove("is-revealed");icon.classList.add("is-spinning");$("#giftEventTitle").textContent="SORTEANDO ITEM...";$("#giftEventDescription").textContent="A caixa misteriosa foi ativada!";modal.hidden=false;const interval=setInterval(()=>{icon.textContent=icons[index++%icons.length];},160),reveal=setTimeout(()=>{clearInterval(interval);icon.classList.remove("is-spinning");icon.textContent=finalIcons[event.type]||"🎁";$("#giftEventTitle").textContent=titles[event.type]||"ITEM REVELADO!";$("#giftEventDescription").textContent=`${source?.name||"Um piloto"} atingiu ${target?.name||"outro piloto"}: -${event.damage} pontos.`;card.classList.add("is-revealed");},2200),close=setTimeout(()=>{modal.hidden=true;card.classList.remove("is-revealed");state.giftEventTimer=null;},6200);state.giftEventTimer={interval,reveal,close};}
$("#openGift").onclick=()=>{const gift=gifts[Math.floor(Math.random()*gifts.length)],pilot=state.pendingGift;state.activeGift=gift;$("#giftIcon").textContent=gift.icon;$("#giftTitle").textContent=gift.title;$("#giftDescription").textContent=gift.text;$("#openGift").hidden=true;if(gift.boost){pilot.score+=gift.boost;renderRace();setTimeout(()=>{const total=state.room.laps*100;$("#mysteryModal").hidden=true;if(pilot.score>=total){state.racing=false;showWinner(pilot);}else nextTurn();},1300);}else{$("#targetGrid").innerHTML=state.pilots.filter(p=>p.id!==pilot.id).map(p=>`<button class="target-button" data-target="${p.id}"><img src="${p.photo}" alt=""><span>${escapeHTML(p.name)}</span></button>`).join("");$("#targetArea").hidden=false;}};
$("#targetGrid").onclick=async e=>{const button=e.target.closest("[data-target]");if(!button)return;const target=state.pilots.find(p=>p.id===button.dataset.target),gift=state.activeGift;try{if(state.cloud){const result=await useRemoteItem(state.room.code,target.id);if(result.expired){hideRemoteItem();toast("O tempo do presente acabou.");await refreshCurrentRoom();return;}clearPendingTimers();$("#giftDescription").textContent=`${target.name} recuou ${gift.damage} pontos!`;$("#targetArea").hidden=true;await refreshCurrentRoom();setTimeout(()=>{$("#mysteryModal").hidden=true;updateRollPermission();},900);}else{target.score=Math.max(0,target.score-gift.damage);$("#giftDescription").textContent=`${target.name} recuou ${gift.damage} pontos!`;$("#targetArea").hidden=true;renderRace();setTimeout(()=>{$("#mysteryModal").hidden=true;nextTurn();},1100);}}catch(error){toast(error.message);}};
function showWinner(p){$("#winnerPhoto").src=p.photo;$("#winnerName").textContent=p.name;$("#winnerStats").textContent=`Completou ${state.room.laps} ${state.room.laps===1?"volta":"voltas"} em ${p.rolls} jogadas.`;$("#winnerModal").hidden=false;}
$("#raceAgain").onclick=startRace; $("#resetRace").onclick=()=>{state.racing=false;openRoom(state.room);};

async function bootstrap(){renderDashboard();setPhoto(makeAvatar("D20"));const requested=new URLSearchParams(location.search).get("sala")?.toUpperCase();if(isSupabaseConfigured){try{const user=await ensureGuestSession();state.cloud=true;state.guestId=user.id;state.rooms=(await listRemoteRooms()).map(normalizeRoom);$("#headerStatus").textContent="Online";renderDashboard();if(requested){const remote=await findRemoteRoom(requested);if(remote)openRoom(normalizeRoom(remote));else toast("Esta sala não existe.");}}catch(error){state.cloud=false;toast(`Modo local: ${error.message}`);}}else if(requested){const room=state.rooms.find(r=>r.code===requested);if(room)openRoom(room);else toast("Esta sala não existe neste navegador.");}}

bootstrap();
